version: "3"

services:
  node:
    container_name: node
    build:
      context: ./node-repo/capNode
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    expose:
      - 8080
    networks:
      - network

  front:
    container_name: front_web
    build:
      context: ./frontend-repo/capweb/
      dockerfile: Dockerfile
    networks:
      - network

networks:
  network:

volumes:
  build_folder: null
